# Docker Compose para desenvolvimento do IFC Digital Twin
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ifc_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Django Web Application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ifc_monitoring
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Worker
  celery_worker:
    build: .
    command: celery -A ifc_monitoring worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ifc_monitoring
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web

  # Celery Beat (Scheduler)
  celery_beat:
    build: .
    command: celery -A ifc_monitoring beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ifc_monitoring
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web

  # Flower (Celery Monitoring)
  flower:
    build: .
    command: celery -A ifc_monitoring flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ifc_monitoring
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - celery_worker
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:

