services:
  - type: web
    name: digital-twin-django
    runtime: python
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "chmod +x start_simple.sh && ./start_simple.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifc-monitoring-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "ifc_monitoring.settings"
      - key: RENDER
        value: "true"
      - key: AUTO_SETUP_DATA
        value: "true"

databases:
  - name: ifc-monitoring-db
    databaseName: ifc_monitoring
    user: ifc_user
    plan: free

