services:
  - type: web
    name: digital-twin-django
    runtime: python
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "chmod +x start_simple.sh && ./start_simple.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifc-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "ifc_monitoring.settings"
      - key: RENDER
        value: "true"
      - key: AUTO_SETUP_DATA
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.10"

# ⚠️ IMPORTANTE: Se o banco ifc-database JÁ EXISTE no outro projeto,
# REMOVA a seção 'databases:' abaixo. Apenas um projeto deve criar o banco.
# 
# Se este é o PRIMEIRO projeto ou o banco NÃO EXISTE ainda, 
# MANTENHA a seção 'databases:' para criar o banco.

databases:
  - name: ifc-database
    plan: free
    databaseName: ifc_monitoring
    user: ifc_user

