services:
  - type: web
    name: digital-twin-django
    runtime: python
    plan: free
    branch: master
    buildCommand: "bash build.sh"
    startCommand: "bash start_simple.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifc-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "ifc_monitoring.settings"
      - key: RENDER
        value: "true"
      - key: AUTO_SETUP_DATA
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.10"

