# Generated by Django 4.2.25 on 2025-10-05 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ifcfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Sensor ativo/inativo'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Valor máximo esperado', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Valor mínimo esperado', null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
