# Generated by Django 5.2.7 on 2025-10-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert_acknowledged_at_alert_acknowledged_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='sensor',
        ),
        migrations.AlterModelOptions(
            name='ifcfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Arquivo IFC (Legado)', 'verbose_name_plural': 'Arquivos IFC (Legado)'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Localização pai na hierarquia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.location'),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
