# Generated by Django 4.2.25 on 2025-10-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='sensor_mana_sensor__6f0272_idx',
            old_name='sensor_man_sensor_id_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='sensor_mana_timesta_2f917a_idx',
            old_name='sensor_man_timesta_123456_idx',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o sensor foi cadastrado', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(help_text='Sensor que gerou este dado', on_delete=django.db.models.deletion.CASCADE, related_name='data_readings', to='sensor_management.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o dado foi coletado', verbose_name='Timestamp'),
        ),
    ]
