# Generated by Django 5.2.7 on 2025-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome descritivo da planta industrial (ex: 'Planta Principal')", max_length=200, verbose_name='Nome da Planta')),
                ('ifc_file', models.FileField(help_text='Arquivo IFC da planta industrial (.ifc)', upload_to='ifc_files/%Y/%m/%d/', validators=[], verbose_name='Arquivo IFC')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da planta industrial', null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Define se esta planta está ativa e disponível para visualização', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano de Construção',
                'verbose_name_plural': 'Planos de Construção',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
