# Generated by Django 4.2.25 on 2025-10-05 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingplan',
            name='ifc_file',
            field=models.FileField(help_text='Arquivo IFC da planta industrial (.ifc)', upload_to='ifc_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ifc'])], verbose_name='Arquivo IFC'),
        ),
        migrations.AlterField(
            model_name='buildingplan',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o arquivo foi enviado', verbose_name='Data de Upload'),
        ),
    ]
