# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_viewer', '0002_alter_buildingplan_ifc_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingplan',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadados extraídos do arquivo IFC (cache)', null=True, verbose_name='Metadados IFC'),
        ),
        migrations.AddField(
            model_name='buildingplan',
            name='metadata_updated_at',
            field=models.DateTimeField(blank=True, help_text='Data da última extração de metadados', null=True, verbose_name='Metadados Atualizados Em'),
        ),
    ]

